<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        $countries=[
        ['AD', 'Andorra', '3101'],
        ['AE', 'United Arab Emirates', '4216'],
        ['AF', 'Afghanistan', '7201'],
        ['AG', 'Antigua and Barbuda', '8402'],
        ['AI', 'Anguilla', '8401'],
        ['AL', 'Albania', '3201'],
        ['AM', 'Armenia', '7202'],
        ['AO', 'Angola', '9201'],
        ['AQ', 'Antarctica', '@@@@'],
        ['AR', 'Argentina', '8201'],
        ['AS', 'American Samoa', '1506'],
        ['AT', 'Austria', '2301'],
        ['AU', 'Australia', '1101'],
        ['AW', 'Aruba', '8403'],
        ['AX', 'Åland', '2408'],
        ['AZ', 'Azerbaijan', '7203'],
        ['BA', 'Bosnia and Herzegovina', '3202'],
        ['BB', 'Barbados', '8405'],
        ['BD', 'Bangladesh', '7101'],
        ['BE', 'Belgium', '2302'],
        ['BF', 'Burkina Faso', '9102'],
        ['BG', 'Bulgaria', '3203'],
        ['BH', 'Bahrain', '4201'],
        ['BI', 'Burundi', '9203'],
        ['BJ', 'Benin', '9101'],
        ['BL', 'Saint Barthélemy', '8431'],
        ['BM', 'Bermuda', '8101'],
        ['BN', 'Brunei', '5201'],
        ['BO', 'Bolivia', '8202'],
        ['BQ', 'Bonaire', '8433'],
        ['BR', 'Brazil', '8203'],
        ['BS', 'Bahamas', '8404'],
        ['BT', 'Bhutan', '7102'],
        ['BV', 'Bouvet Island', '2406'],
        ['BW', 'Botswana', '9202'],
        ['BY', 'Belarus', '3301'],
        ['BZ', 'Belize', '8301'],
        ['CA', 'Canada', '8102'],
        ['CC', 'Cocos [Keeling] Islands', '1199'],
        ['CD', 'Democratic Republic of the Congo', '9108'],
        ['CF', 'Central African Republic', '9105'],
        ['CG', 'Republic of the Congo', '9107'],
        ['CH', 'Switzerland', '2311'],
        ['CI', 'Ivory Coast', '9111'],
        ['CK', 'Cook Islands', '1501'],
        ['CL', 'Chile', '8204'],
        ['CM', 'Cameroon', '9103'],
        ['CN', 'China', '6101'],
        ['CO', 'Colombia', '8205'],
        ['CR', 'Costa Rica', '8302'],
        ['CU', 'Cuba', '8407'],
        ['CV', 'Cape Verde', '9104'],
        ['CW', 'Curacao', '8434'],
        ['CX', 'Christmas Island', '1199'],
        ['CY', 'Cyprus', '3205'],
        ['CZ', 'Czech Republic', '3302'],
        ['DE', 'Germany', '2304'],
        ['DJ', 'Djibouti', '9205'],
        ['DK', 'Denmark', '2401'],
        ['DM', 'Dominica', '8408'],
        ['DO', 'Dominican Republic', '8411'],
        ['DZ', 'Algeria', '4101'],
        ['EC', 'Ecuador', '8206'],
        ['EE', 'Estonia', '3303'],
        ['EG', 'Egypt', '4102'],
        ['EH', 'Western Sahara', '4107'],
        ['ER', 'Eritrea', '9206'],
        ['ES', 'Spain', '3108'],
        ['ET', 'Ethiopia', '9207'],
        ['FI', 'Finland', '2403'],
        ['FJ', 'Fiji', '1502'],
        ['FK', 'Falkland Islands', '8207'],
        ['FM', 'Micronesia', '1404'],
        ['FO', 'Faroe Islands', '2402'],
        ['FR', 'France', '2303'],
        ['GA', 'Gabon', '9113'],
        ['GB', 'United Kingdom', '2102'],
        ['GD', 'Grenada', '8412'],
        ['GE', 'Georgia', '7204'],
        ['GF', 'French Guiana', '8208'],
        ['GG', 'Guernsey', '2107'],
        ['GH', 'Ghana', '9115'],
        ['GI', 'Gibraltar', '3102'],
        ['GL', 'Greenland', '2404'],
        ['GM', 'Gambia', '9114'],
        ['GN', 'Guinea', '9116'],
        ['GP', 'Guadeloupe', '8413'],
        ['GQ', 'Equatorial Guinea', '9112'],
        ['GR', 'Greece', '3207'],
        ['GS', 'South Georgia and the South Sandwich Islands', '@@@@'],
        ['GT', 'Guatemala', '8304'],
        ['GU', 'Guam', '1401'],
        ['GW', 'Guinea-Bissau', '9117'],
        ['GY', 'Guyana', '8211'],
        ['HK', 'Hong Kong', '6102'],
        ['HM', 'Heard Island and McDonald Islands', '1199'],
        ['HN', 'Honduras', '8305'],
        ['HR', 'Croatia', '3204'],
        ['HT', 'Haiti', '8414'],
        [ 'HU', 'Hungary', '3304'],
        [ 'ID', 'Indonesia', '5202'],
        [ 'IE', 'Ireland', '2201'],
        [ 'IL', 'Israel', '4205'],
        [ 'IM', 'Isle of Man', '2103'],
        [ 'IN', 'India', '7103'],
        [ 'IO', 'British Indian Ocean Territory', '@@@@'],
        [ 'IQ', 'Iraq', '4204'],
        [ 'IR', 'Iran', '4203'],
        [ 'IS', 'Iceland', '2405'],
        [ 'IT', 'Italy', '3104'],
        [ 'JE', 'Jersey', '2108'],
        [ 'JM', 'Jamaica', '8415'],
        [ 'JO', 'Jordan', '4206'],
        [ 'JP', 'Japan', '6201'],
        [ 'KE', 'Kenya', '9208'],
        [ 'KG', 'Kyrgyzstan', '7206'],
        [ 'KH', 'Cambodia', '5102'],
        [ 'KI', 'Kiribati', '1402'],
        [ 'KM', 'Comoros', '9204'],
        [ 'KN', 'Saint Kitts and Nevis', '8422'],
        [ 'KP', 'North Korea', '6202'],
        [ 'KR', 'South Korea', '6203'],
        [ 'KW', 'Kuwait', '4207'],
        [ 'KY', 'Cayman Islands', '8406'],
        [ 'KZ', 'Kazakhstan', '7205'],
        [ 'LA', 'Laos', '5103'],
        [ 'LB', 'Lebanon', '4208'],
        [ 'LC', 'Saint Lucia', '8423'],
        [ 'LI', 'Liechtenstein', '2305'],
        [ 'LK', 'Sri Lanka', '7107'],
        [ 'LR', 'Liberia', '9118'],
        [ 'LS', 'Lesotho', '9211'],
        [ 'LT', 'Lithuania', '3306'],
        [ 'LU', 'Luxembourg', '2306'],
        [ 'LV', 'Latvia', '3305'],
        [ 'LY', 'Libya', '4103'],
        [ 'MA', 'Morocco', '4104'],
        [ 'MC', 'Monaco', '2307'],
        [ 'MD', 'Moldova', '3208'],
        [ 'ME', 'Montenegro', '3214'],
        [ 'MF', 'Saint Martin', '8432'],
        [ 'MG', 'Madagascar', '9212'],
        [ 'MH', 'Marshall Islands', '1403'],
        [ 'MK', 'Macedonia', '3206'],
        [ 'ML', 'Mali', '9121'],
        [ 'MM', 'Myanmar [Burma]', '5101'],
        [ 'MN', 'Mongolia', '6104'],
        [ 'MO', 'Macao', '6103'],
        [ 'MP', 'Northern Mariana Islands', '1406'],
        [ 'MQ', 'Martinique', '8416'],
        [ 'MR', 'Mauritania', '9122'],
        [ 'MS', 'Montserrat', '8417'],
        [ 'MT', 'Malta', '3105'],
        [ 'MU', 'Mauritius', '9214'],
        [ 'MV', 'Maldives', '7104'],
        [ 'MW', 'Malawi', '9213'],
        [ 'MX', 'Mexico', '8306'],
        [ 'MY', 'Malaysia', '5203'],
        [ 'MZ', 'Mozambique', '9216'],
        [ 'NA', 'Namibia', '9217'],
        [ 'NC', 'New Caledonia', '1301'],
        [ 'NE', 'Niger', '9123'],
        [ 'NF', 'Norfolk Island', '1102'],
        [ 'NG', 'Nigeria', '9124'],
        [ 'NI', 'Nicaragua', '8307'],
        [ 'NL', 'Netherlands', '2308'],
        [ 'NO', 'Norway', '2406'],
        [ 'NP', 'Nepal', '7105'],
        [ 'NR', 'Nauru', '1405'],
        [ 'NU', 'Niue', '1504'],
        [ 'NZ', 'New Zealand', '1201'],
        [ 'OM', 'Oman', '4211'],
        [ 'PA', 'Panama', '8308'],
        [ 'PE', 'Peru', '8213'],
        [ 'PF', 'French Polynesia', '1503'],
        [ 'PG', 'Papua New Guinea', '1302'],
        [ 'PH', 'Philippines', '5204'],
        [ 'PK', 'Pakistan', '7106'],
        [ 'PL', 'Poland', '3307'],
        [ 'PM', 'Saint Pierre and Miquelon', '8103'],
        [ 'PN', 'Pitcairn Islands', '1513'],
        [ 'PR', 'Puerto Rico', '8421'],
        [ 'PS', 'Palestine', '@@@@'],
        [ 'PT', 'Portugal', '3106'],
        [ 'PW', 'Palau', '1407'],
        [ 'PY', 'Paraguay', '8212'],
        [ 'QA', 'Qatar', '4212'],
        [ 'RE', 'Réunion', '9218'],
        [ 'RO', 'Romania', '3211'],
        [ 'RS', 'Serbia', '3215'],
        [ 'RU', 'Russia', '3308'],
        [ 'RW', 'Rwanda', '9221'],
        [ 'SA', 'Saudi Arabia', '4213'],
        [ 'SB', 'Solomon Islands', '1303'],
        [ 'SC', 'Seychelles', '9223'],
        [ 'SD', 'Sudan', '4105'],
        [ 'SE', 'Sweden', '2407'],
        [ 'SG', 'Singapore', '5205'],
        [ 'SH', 'Saint Helena', '9222'],
        [ 'SI', 'Slovenia', '3212'],
        [ 'SJ', 'Svalbard and Jan Mayen', '@@@@'],
        [ 'SK', 'Slovakia', '3311'],
        [ 'SL', 'Sierra Leone', '9127'],
        [ 'SM', 'San Marino', '3107'],
        [ 'SN', 'Senegal', '9126'],
        [ 'SO', 'Somalia', '9224'],
        [ 'SR', 'Suriname', '8214'],
        [ 'SS', 'South Sudan', '4111'],
        [ 'ST', 'São Tomé and Príncipe', '9125'],
        [ 'SV', 'El Salvador', '8303'],
        [ 'SX', 'Sint Maarten', '8435'],
        [ 'SY', 'Syria', '4214'],
        [ 'SZ', 'Swaziland', '9226'],
        [ 'TC', 'Turks and Caicos Islands', '8426'],
        [ 'TD', 'Chad', '9106'],
        [ 'TF', 'French Southern Territories', '1601'],
        [ 'TG', 'Togo', '9128'],
        [ 'TH', 'Thailand', '5104'],
        [ 'TJ', 'Tajikistan', '7207'],
        [ 'TK', 'Tokelau', '1507'],
        [ 'TL', 'East Timor', '5206'],
        [ 'TM', 'Turkmenistan', '7208'],
        [ 'TN', 'Tunisia', '4106'],
        [ 'TO', 'Tonga', '1508'],
        [ 'TR', 'Turkey', '4215'],
        [ 'TT', 'Trinidad and Tobago', '8425'],
        [ 'TV', 'Tuvalu', '1511'],
        [ 'TW', 'Taiwan', '6105'],
        [ 'TZ', 'Tanzania', '9227'],
        [ 'UA', 'Ukraine', '3312'],
        [ 'UG', 'Uganda', '9228'],
        [ 'UM', 'U.S. Minor Outlying Islands', '@@@@'],
        [ 'US', 'United States', '8104'],
        [ 'UY', 'Uruguay', '8215'],
        [ 'UZ', 'Uzbekistan', '7211'],
        [ 'VA', 'Vatican City', '@@@@'],
        [ 'VC', 'Saint Vincent and the Grenadines', '8424'],
        [ 'VE', 'Venezuela', '8216'],
        [ 'VG', 'British Virgin Islands', '8427'],
        [ 'VI', 'U.S. Virgin Islands', '8428'],
        [ 'VN', 'Vietnam', '5105'],
        [ 'VU', 'Vanuatu', '1304'],
        [ 'WF', 'Wallis and Futuna', '1512'],
        [ 'WS', 'Samoa', '1505'],
        [ 'XK', 'Kosovo', '3216'],
        [ 'YE', 'Yemen', '4217'],
        [ 'YT', 'Mayotte', '9215'],
        [ 'ZA', 'South Africa', '9225'],
        [ 'ZM', 'Zambia', '9231'],
        [ 'ZW', 'Zimbabwe', '9232']
        ];

        foreach ($countries as $country) {
            Country::create(['code' => $country[0],'name'=>$country[1],'sacc'=>$country[2]]);
        }
    }
}
